blank_issues_enabled: false
contact_links:
  - name: AiMazing related issues
    url: https://github.com/fenago/AiMazing/issues/new/choose
    about: Report issues related to AiMazing by Dr. Ernesto Lee
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other AiMazing users.
